// Simple Node.js test script for AI content generation
const fetch = require('node-fetch');
require('dotenv').config({ path: '.env.local' });

async function testAPI() {
  console.log('🚀 Testing Houston Marketing Machine AI API...\n');
  
  const testData = {
    topic: 'Houston Heights real estate investment',
    contentType: 'market_update',
    platform: 'instagram'
  };
  
  try {
    console.log('📡 Calling API with data:', testData);
    
    const response = await fetch('http://localhost:3000/api/content/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(testData)
    });
    
    const result = await response.json();
    
    if (result.success) {
      console.log('\n✅ AI CONTENT GENERATION SUCCESS!');
      console.log('Generated by:', result.data.generatedBy);
      console.log('Topic:', result.data.topic);
      console.log('Platform:', result.data.platform);
      console.log('\n📝 Generated Content:');
      console.log('=' .repeat(60));
      console.log(result.data.content);
      console.log('=' .repeat(60));
      console.log('\n🎉 Houston Marketing Machine AI is WORKING!');
    } else {
      console.log('❌ API Error:', result.error);
      console.log('Response:', result);
    }
  } catch (error) {
    console.log('❌ Test failed:', error.message);
    console.log('Make sure the dev server is running: npm run dev');
  }
}

testAPI();
